

create Database NEW_DATA
CREATE TABLE  EMPLOYEESS(EMP_ID INT,EMP_NAME VARCHAR(60),EMP_CONTACT INT,EMP_MAIL VARCHAR(90),
EMP_DEPARTMENT VARCHAR(80),EMP_CITY VARCHAR(80))

INSERT INTO EMPLOYEESS VALUES(1,'RAKESH',96663323,'rakesh404@gmai.com','COMPUTER','AHEMDABAD') 
INSERT INTO EMPLOYEESS VALUES(2,'SHIVA',89222121,'shiva2304@gmai.com','ACCOUNT','MUMBAI') 
INSERT INTO EMPLOYEESS VALUES(3,'KEVAL',8983222,'keval@gmai.com','MANAGEMENT','MUMBAI') 
INSERT INTO EMPLOYEESS VALUES(4,'RINA',78722121,'rina39304@gmai.com','ACCOUNT','AHEMDABAD') 
INSERT INTO EMPLOYEESS VALUES(5,'SIMA',67899002,'siam33003@gmai.com','ACCOUNT','VISHAKHAPATANAM') 
INSERT INTO EMPLOYEESS VALUES(6,'ROHAN',90212123,'rohank@gmai.com','COMPUTER','VISHAKHAPATANAM') 
INSERT INTO EMPLOYEESS VALUES(7,'KETAN',77345589,'ketan223@gmai.com','COMPUTER','MUMBAI') 
INSERT INTO EMPLOYEESS VALUES(8,'AMAN',667483300,'aman433@gmai.com','MANAGEMENT','AHEMDABAD') 

SELECT * FROM EMPLOYEESS 
  
 Fun_EmployeeInformation()   
    returns table       
    as      
    return(select * from EMPLOYEESS  )     



DROP TABLE EMPLOYEESS

