

---First Normal Form----

Create Table Emp(EMP_ID INT,EMP_NAME varchar(80),EMP_PHONE INT,EMP_STATE VARCHAR(50))

INSERT INTO EMP VALUES(1,'TOM',34423243,'MAHA')
INSERT INTO EMP VALUES(1,'TOM',345555,'MAHA')

SELECT * FROM EMP 