


CREATE TABLE CUSTOMER (CUST_ID INT,CUST_NAME VARCHAR(60),TELE_NO INT)

CREATE TABLE ORDERS_S(ORDER_ID INT,ORDER_DATE DATE,CUST_ID INT,PRODUCT_NAME VARCHAR(70),
QUNTITY INT,RATE INT)


INSERT INTO CUSTOMER(CUST_ID,CUST_NAME,TELE_NO)
VALUES(1123,'WALTER',2234556),
(1124,'HENRY',223445),
(1125,'EMA',223433),
(1126,'HARRY',223665),
(1127,'GARES',229956),
(1128,'DICKINS',2238895);

INSERT INTO ORDERS_S(ORDER_ID,ORDER_DATE,CUST_ID,PRODUCT_NAME,QUNTITY,RATE)
VALUES(1,'2022-9-1',1123,'BISCUIT',4,45),
(2,'2022-9-2',1124,'BISCUIT',4,44),
(3,'2022-9-3',1125,'BISCUIT',6,47),
(4,'2022-9-4',1126,'BISCUIT',3,45),
(5,'2022-9-5',1127,'BISCUIT',7,42),
(6,'2022-9-5',1128,'BISCUIT',8,47);

SELECT * FROM CUSTOMER
SELECT * FROM ORDERS_S

SELECT CUSTOMER.CUST_ID,CUSTOMER.CUST_NAME,CUSTOMER.TELE_NO,ORDERS_S.ORDER_DATE,ORDERS_S.PRODUCT_NAME,ORDERS_S.CUST_ID
FROM CUSTOMER
INNER JOIN ORDERS_S
ON CUSTOMER.CUST_ID=ORDERS_S.CUST_ID;

SELECT CUSTOMER.CUST_ID,CUSTOMER.CUST_NAME,CUSTOMER.TELE_NO,ORDERS_S.ORDER_DATE,ORDERS_S.PRODUCT_NAME,ORDERS_S.CUST_ID
FROM CUSTOMER
CROSS JOIN ORDERS_S
WHERE CUSTOMER.CUST_ID=ORDERS_S.CUST_ID;

SELECT CUSTOMER.CUST_ID,CUSTOMER.CUST_NAME,CUSTOMER.TELE_NO,ORDERS_S.ORDER_DATE,ORDERS_S.PRODUCT_NAME,ORDERS_S.CUST_ID
FROM CUSTOMER
LEFT OUTER JOIN ORDERS_S
ON CUSTOMER.CUST_ID=ORDERS_S.CUST_ID;

SELECT CUSTOMER.CUST_ID,CUSTOMER.CUST_NAME,CUSTOMER.TELE_NO,ORDERS_S.ORDER_DATE,ORDERS_S.PRODUCT_NAME,ORDERS_S.CUST_ID
FROM CUSTOMER
RIGHT OUTER JOIN ORDERS_S
ON CUSTOMER.CUST_ID=ORDERS_S.CUST_ID;

SELECT CUSTOMER.CUST_ID,CUSTOMER.CUST_NAME,CUSTOMER.TELE_NO,ORDERS_S.ORDER_DATE,ORDERS_S.PRODUCT_NAME,ORDERS_S.CUST_ID
FROM CUSTOMER
FULL OUTER JOIN ORDERS_S
ON CUSTOMER.CUST_ID=ORDERS_S.CUST_ID;

SELECT S1.CUST_NAME,S3.TELE_NO
FROM CUSTOMER S1,CUSTOMER S3
WHERE S1.CUST_ID <> S2.CUST_ID AND S1.CUST_NAME=S2.CUST_NAME
ORDER BY S2.CUST_NAME;